const SIZE_DATA = {
  "mhf1": [
    {
      "id": 50,
      "name": "Ashen Lao-Shan Lung",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Rock Mountain Dragon",
      "biggestPct": 100,
      "biggestQuest": "Rock Mountain Dragon",
      "questCount": 2
    },
    {
      "id": 49,
      "name": "Azure Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": null,
      "kingCrownPct": 1.27,
      "smallestPct": 85,
      "smallestQuest": "A Troublesome Pair",
      "biggestPct": 138,
      "biggestQuest": "Slay the Rathalos!",
      "questCount": 9,
      "kingCrownCm": 2069.3,
      "smallestCm": 1385,
      "biggestCm": 2240.4
    },
    {
      "id": 22,
      "name": "Basarios",
      "baseCm": 1297.6,
      "minCrownPct": null,
      "kingCrownPct": 1.29,
      "smallestPct": 94,
      "smallestQuest": "Basarios: Invisible Terror",
      "biggestPct": 138,
      "biggestQuest": "Basarios: Invisible Terror",
      "questCount": 21,
      "kingCrownCm": 1673.9,
      "smallestCm": 1213.3,
      "biggestCm": 1784.2
    },
    {
      "id": 43,
      "name": "Black Diablos",
      "baseCm": 1993.4,
      "minCrownPct": null,
      "kingCrownPct": 1.39,
      "smallestPct": 100,
      "smallestQuest": "Four Horns",
      "biggestPct": 150,
      "biggestQuest": "The Runaway Diablos",
      "questCount": 4,
      "kingCrownCm": 2770.8,
      "smallestCm": 1999.4,
      "biggestCm": 2990.1
    },
    {
      "id": 47,
      "name": "Black Gravios",
      "baseCm": 2099.9,
      "minCrownPct": null,
      "kingCrownPct": 1.35,
      "smallestPct": 102,
      "smallestQuest": "Volcanic Valor",
      "biggestPct": 150,
      "biggestQuest": "Volcanic Valor",
      "questCount": 5,
      "kingCrownCm": 2834.9,
      "smallestCm": 2141.9,
      "biggestCm": 3149.8
    },
    {
      "id": 38,
      "name": "Blue Yian Kut-Ku",
      "baseCm": 919.8,
      "minCrownPct": null,
      "kingCrownPct": 1.22,
      "smallestPct": 90,
      "smallestQuest": "Jungle Menace",
      "biggestPct": 133,
      "biggestQuest": "Jungle Menace",
      "questCount": 7,
      "kingCrownCm": 1122.2,
      "smallestCm": 827.8,
      "biggestCm": 1223.3
    },
    {
      "id": 8,
      "name": "Cephadrome",
      "baseCm": 1538.3,
      "minCrownPct": null,
      "kingCrownPct": 1.22,
      "smallestPct": 89,
      "smallestQuest": "The Two Sand Shadows",
      "biggestPct": 131,
      "biggestQuest": "The Two Sand Shadows",
      "questCount": 15,
      "kingCrownCm": 1876.7,
      "smallestCm": 1372.9,
      "biggestCm": 2019
    },
    {
      "id": 36,
      "name": "Crimson Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Advent of Calamity",
      "biggestPct": 100,
      "biggestQuest": "Advent of Calamity",
      "questCount": 4
    },
    {
      "id": 14,
      "name": "Diablos",
      "baseCm": 1993.4,
      "minCrownPct": null,
      "kingCrownPct": 1.39,
      "smallestPct": 100,
      "smallestQuest": "The Runaway Diablos",
      "biggestPct": 135,
      "biggestQuest": "The Runaway Diablos",
      "questCount": 11,
      "kingCrownCm": 2770.8,
      "smallestCm": 1993.4,
      "biggestCm": 2681.5
    },
    {
      "id": 2,
      "name": "Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Legendary Black Dragon",
      "biggestPct": 100,
      "biggestQuest": "Legendary Black Dragon",
      "questCount": 6
    },
    {
      "id": 28,
      "name": "Gendrome",
      "baseCm": 732.1,
      "minCrownPct": null,
      "kingCrownPct": 1.23,
      "smallestPct": 96,
      "smallestQuest": "Slay the Gendrome!",
      "biggestPct": 120,
      "biggestQuest": "The Burrowing Monster",
      "questCount": 7,
      "kingCrownCm": 900.5,
      "smallestCm": 702.8,
      "biggestCm": 876.3
    },
    {
      "id": 42,
      "name": "Gold Rathian",
      "baseCm": 1645.6,
      "minCrownPct": null,
      "kingCrownPct": 1.29,
      "smallestPct": 85,
      "smallestQuest": "Queen of the Jungle",
      "biggestPct": 125,
      "biggestQuest": "Queen of the Jungle",
      "questCount": 4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1398.8,
      "biggestCm": 2057
    },
    {
      "id": 17,
      "name": "Gravios",
      "baseCm": 2099.9,
      "minCrownPct": null,
      "kingCrownPct": 1.35,
      "smallestPct": 95,
      "smallestQuest": "Handle With Care!",
      "biggestPct": 150,
      "biggestQuest": "Powderstone Festival",
      "questCount": 16,
      "kingCrownCm": 2834.9,
      "smallestCm": 1994.9,
      "biggestCm": 3149.8
    },
    {
      "id": 46,
      "name": "Green Plesioth",
      "baseCm": 2315.2,
      "minCrownPct": null,
      "kingCrownPct": 1.34,
      "smallestPct": 99,
      "smallestQuest": "Water Wyvern in the Jungle",
      "biggestPct": 145,
      "biggestQuest": "Water Wyvern in the Jungle",
      "questCount": 5,
      "kingCrownCm": 3102.4,
      "smallestCm": 2282.8,
      "biggestCm": 3357
    },
    {
      "id": 20,
      "name": "Gypceros",
      "baseCm": 1013.7,
      "minCrownPct": null,
      "kingCrownPct": 1.25,
      "smallestPct": 99,
      "smallestQuest": "Slay the Gypceros!",
      "biggestPct": 122,
      "biggestQuest": "Trouble in the Swamp",
      "questCount": 19,
      "kingCrownCm": 1267.1,
      "smallestCm": 1001.5,
      "biggestCm": 1236.5
    },
    {
      "id": 31,
      "name": "Iodrome",
      "baseCm": 774.6,
      "minCrownPct": null,
      "kingCrownPct": 1.36,
      "smallestPct": 95,
      "smallestQuest": "Fang of the Iodrome!",
      "biggestPct": 150,
      "biggestQuest": "Powderstone Festival",
      "questCount": 11,
      "kingCrownCm": 1053.5,
      "smallestCm": 735.9,
      "biggestCm": 1161.9
    },
    {
      "id": 15,
      "name": "Khezu",
      "baseCm": 873.2,
      "minCrownPct": null,
      "kingCrownPct": 1.35,
      "smallestPct": 95,
      "smallestQuest": "Fang of the Iodrome!",
      "biggestPct": 131,
      "biggestQuest": "The Shadow in the Cave",
      "questCount": 16,
      "kingCrownCm": 1178.8,
      "smallestCm": 829.5,
      "biggestCm": 1144.8
    },
    {
      "id": 33,
      "name": "Kirin",
      "baseCm": 464.3,
      "minCrownPct": null,
      "kingCrownPct": 1.77,
      "smallestPct": 100,
      "smallestQuest": "On the Trail of the Beast!",
      "biggestPct": 200,
      "biggestQuest": "Thunder and Lightning",
      "questCount": 7,
      "kingCrownCm": 821.8,
      "smallestCm": 464.3,
      "biggestCm": 928.6
    },
    {
      "id": 7,
      "name": "Lao-Shan Lung",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "A Giant Dragon Invades!",
      "biggestPct": 100,
      "biggestQuest": "A Giant Dragon Invades!",
      "questCount": 4
    },
    {
      "id": 26,
      "name": "Monoblos",
      "baseCm": 2004.2,
      "minCrownPct": null,
      "kingCrownPct": 1.27,
      "smallestPct": 98,
      "smallestQuest": "Horn of the Monoblos",
      "biggestPct": 117,
      "biggestQuest": "Horn of the Monoblos",
      "questCount": 6,
      "kingCrownCm": 2545.3,
      "smallestCm": 1961.1,
      "biggestCm": 2353.3
    },
    {
      "id": 37,
      "name": "Pink Rathian",
      "baseCm": 1645.6,
      "minCrownPct": null,
      "kingCrownPct": 1.29,
      "smallestPct": 85,
      "smallestQuest": "A Troublesome Pair",
      "biggestPct": 139,
      "biggestQuest": "Queen of the Desert",
      "questCount": 8,
      "kingCrownCm": 2122.8,
      "smallestCm": 1398.8,
      "biggestCm": 2283.3
    },
    {
      "id": 21,
      "name": "Plesioth",
      "baseCm": 2315.2,
      "minCrownPct": null,
      "kingCrownPct": 1.34,
      "smallestPct": 100,
      "smallestQuest": "The Lady Gourmet",
      "biggestPct": 131,
      "biggestQuest": "Water Wyvern in the Jungle",
      "questCount": 14,
      "kingCrownCm": 3102.4,
      "smallestCm": 2315.2,
      "biggestCm": 3035.2
    },
    {
      "id": 39,
      "name": "Purple Gypceros",
      "baseCm": 1013.7,
      "minCrownPct": null,
      "kingCrownPct": 1.25,
      "smallestPct": 92,
      "smallestQuest": "Slay the Gypceros!",
      "biggestPct": 135,
      "biggestQuest": "Slay the Gypceros!",
      "questCount": 4,
      "kingCrownCm": 1267.1,
      "smallestCm": 930.6,
      "biggestCm": 1368.5
    },
    {
      "id": 11,
      "name": "Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": null,
      "kingCrownPct": 1.27,
      "smallestPct": 92,
      "smallestQuest": "The Smoke Clad King",
      "biggestPct": 135,
      "biggestQuest": "The Smoke Clad King",
      "questCount": 26,
      "kingCrownCm": 2069.3,
      "smallestCm": 1495.8,
      "biggestCm": 2199.7
    },
    {
      "id": 1,
      "name": "Rathian",
      "baseCm": 1645.6,
      "minCrownPct": null,
      "kingCrownPct": 1.29,
      "smallestPct": 92,
      "smallestQuest": "Wyverns of Land and Sky",
      "biggestPct": 135,
      "biggestQuest": "Wyverns of Land and Sky",
      "questCount": 24,
      "kingCrownCm": 2122.8,
      "smallestCm": 1510.7,
      "biggestCm": 2221.6
    },
    {
      "id": 45,
      "name": "Red Khezu",
      "baseCm": 873.2,
      "minCrownPct": null,
      "kingCrownPct": 1.35,
      "smallestPct": 99,
      "smallestQuest": "Wyvern in the Darkness",
      "biggestPct": 146,
      "biggestQuest": "Wyvern in the Darkness",
      "questCount": 3,
      "kingCrownCm": 1178.8,
      "smallestCm": 868.4,
      "biggestCm": 1277.1
    },
    {
      "id": 41,
      "name": "Silver Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": null,
      "kingCrownPct": 1.27,
      "smallestPct": 85,
      "smallestQuest": "Slay the Rathalos!",
      "biggestPct": 125,
      "biggestQuest": "Slay the Rathalos!",
      "questCount": 4,
      "kingCrownCm": 2069.3,
      "smallestCm": 1385,
      "biggestCm": 2036.8
    },
    {
      "id": 27,
      "name": "Velocidrome",
      "baseCm": 738.4,
      "minCrownPct": null,
      "kingCrownPct": 1.23,
      "smallestPct": 96,
      "smallestQuest": "The Velociprey Lords",
      "biggestPct": 120,
      "biggestQuest": "Attack of the Yian Kut-Ku",
      "questCount": 8,
      "kingCrownCm": 908.2,
      "smallestCm": 708.9,
      "biggestCm": 883.9
    },
    {
      "id": 44,
      "name": "White Monoblos",
      "baseCm": 2004.2,
      "minCrownPct": null,
      "kingCrownPct": 1.27,
      "smallestPct": 94,
      "smallestQuest": "Horn of the Monoblos",
      "biggestPct": 138,
      "biggestQuest": "Horn of the Monoblos",
      "questCount": 1,
      "kingCrownCm": 2545.3,
      "smallestCm": 1873.9,
      "biggestCm": 2755.8
    },
    {
      "id": 40,
      "name": "Yian Garuga",
      "baseCm": 1031.7,
      "minCrownPct": null,
      "kingCrownPct": 1.31,
      "smallestPct": 100,
      "smallestQuest": "The Rage of Yian Garuga",
      "biggestPct": 100,
      "biggestQuest": "The Rage of Yian Garuga",
      "questCount": 5,
      "kingCrownCm": 1351.5,
      "smallestCm": 1031.7,
      "biggestCm": 1031.7
    },
    {
      "id": 6,
      "name": "Yian Kut-Ku",
      "baseCm": 919.8,
      "minCrownPct": null,
      "kingCrownPct": 1.22,
      "smallestPct": 50,
      "smallestQuest": "The Illusion of Kut-Ku",
      "biggestPct": 120,
      "biggestQuest": "Attack of the Yian Kut-Ku",
      "questCount": 29,
      "kingCrownCm": 1122.2,
      "smallestCm": 459.9,
      "biggestCm": 1101
    }
  ],
  "mhf2": [
    {
      "id": 76,
      "name": "Akantor",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Rise to the Summit",
      "biggestPct": 100,
      "biggestQuest": "Rise to the Summit",
      "questCount": 1
    },
    {
      "id": 50,
      "name": "Ashen Lao-Shan Lung",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Lao-Shan Lung Draws Near!",
      "biggestPct": 100,
      "biggestQuest": "Lao-Shan Lung Draws Near!",
      "questCount": 1
    },
    {
      "id": 49,
      "name": "Azure Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.27,
      "smallestPct": 88,
      "smallestQuest": "Attack of the Rathalos",
      "biggestPct": 140,
      "biggestQuest": "Blue Sky, Pink Earth",
      "questCount": 4,
      "minCrownCm": 1466.5,
      "kingCrownCm": 2069.3,
      "smallestCm": 1440.4,
      "biggestCm": 2281.2
    },
    {
      "id": 22,
      "name": "Basarios",
      "baseCm": 1297.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 89,
      "smallestQuest": "Basarios: Unseen Peril",
      "biggestPct": 131,
      "biggestQuest": "Basarios: Unseen Peril",
      "questCount": 8,
      "minCrownCm": 1206.8,
      "kingCrownCm": 1673.9,
      "smallestCm": 1158.1,
      "biggestCm": 1703.1
    },
    {
      "id": 43,
      "name": "Black Diablos",
      "baseCm": 1993.4,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.39,
      "smallestPct": 96,
      "smallestQuest": "Four Horns",
      "biggestPct": 141,
      "biggestQuest": "Four Horns",
      "questCount": 5,
      "minCrownCm": 1933.6,
      "kingCrownCm": 2770.8,
      "smallestCm": 1914.7,
      "biggestCm": 2815.7
    },
    {
      "id": 47,
      "name": "Black Gravios",
      "baseCm": 2099.9,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.35,
      "smallestPct": 94,
      "smallestQuest": "Black Rock in the Swamp",
      "biggestPct": 144,
      "biggestQuest": "The Hot, Dark Wind",
      "questCount": 6,
      "minCrownCm": 2036.9,
      "kingCrownCm": 2834.9,
      "smallestCm": 1963.4,
      "biggestCm": 3018.6
    },
    {
      "id": 51,
      "name": "Blangonga",
      "baseCm": 860,
      "minCrownPct": 0.99,
      "kingCrownPct": 1.38,
      "smallestPct": 97,
      "smallestQuest": "Two Roars in the Snow",
      "biggestPct": 143,
      "biggestQuest": "Two Roars in the Snow",
      "questCount": 13,
      "minCrownCm": 851.4,
      "kingCrownCm": 1186.8,
      "smallestCm": 834.2,
      "biggestCm": 1229.8
    },
    {
      "id": 38,
      "name": "Blue Yian Kut-Ku",
      "baseCm": 919.8,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.22,
      "smallestPct": 87,
      "smallestQuest": "Trapped by Yian Kut-Ku ",
      "biggestPct": 131,
      "biggestQuest": "Gathering - Forest and Hills",
      "questCount": 8,
      "minCrownCm": 827.8,
      "kingCrownCm": 1122.2,
      "smallestCm": 797.5,
      "biggestCm": 1207.2
    },
    {
      "id": 68,
      "name": "Bulldrome",
      "baseCm": 566,
      "minCrownPct": 0.98,
      "kingCrownPct": 1.3,
      "smallestPct": 91,
      "smallestQuest": "The Purple Poison Menace",
      "biggestPct": 210,
      "biggestQuest": "Challenge Quest 6",
      "questCount": 17,
      "minCrownCm": 554.7,
      "kingCrownCm": 735.8,
      "smallestCm": 514.8,
      "biggestCm": 1188.6
    },
    {
      "id": 8,
      "name": "Cephadrome",
      "baseCm": 1538.3,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.22,
      "smallestPct": 89,
      "smallestQuest": "Pursuit of the Sand Wyvern",
      "biggestPct": 131,
      "biggestQuest": "Pursuit of the Sand Wyvern",
      "questCount": 7,
      "minCrownCm": 1430.6,
      "kingCrownCm": 1876.7,
      "smallestCm": 1372.9,
      "biggestCm": 2019
    },
    {
      "id": 59,
      "name": "Chameleos",
      "baseCm": 1744,
      "minCrownPct": 0.96,
      "kingCrownPct": 1.41,
      "smallestPct": 95,
      "smallestQuest": "The Elder Dragon of Mist",
      "biggestPct": 150,
      "biggestQuest": "The Elder Dragon of Mist",
      "questCount": 6,
      "minCrownCm": 1674.2,
      "kingCrownCm": 2459,
      "smallestCm": 1656.8,
      "biggestCm": 2616
    },
    {
      "id": 52,
      "name": "Congalala",
      "baseCm": 984,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.25,
      "smallestPct": 94,
      "smallestQuest": "Conga Counterattack!",
      "biggestPct": 138,
      "biggestQuest": "Conga Counterattack!",
      "questCount": 13,
      "minCrownCm": 954.5,
      "kingCrownCm": 1230,
      "smallestCm": 920,
      "biggestCm": 1353
    },
    {
      "id": 36,
      "name": "Crimson Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "The Crimson Disaster",
      "biggestPct": 105,
      "biggestQuest": "The Crimson Disaster",
      "questCount": 2
    },
    {
      "id": 48,
      "name": "Daimyo Hermitaur",
      "baseCm": 1044,
      "minCrownPct": 0.88,
      "kingCrownPct": 1.23,
      "smallestPct": 85,
      "smallestQuest": "Ultimate Crab Dinner",
      "biggestPct": 130,
      "biggestQuest": "Strong Sword, Strong Shield",
      "questCount": 20,
      "minCrownCm": 918.7,
      "kingCrownCm": 1284.1,
      "smallestCm": 887.4,
      "biggestCm": 1356.8
    },
    {
      "id": 14,
      "name": "Diablos",
      "baseCm": 1993.4,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.39,
      "smallestPct": 96,
      "smallestQuest": "Four Horns",
      "biggestPct": 148,
      "biggestQuest": "「マ）王　片角のマオウ",
      "questCount": 7,
      "minCrownCm": 1933.6,
      "kingCrownCm": 2770.8,
      "smallestCm": 1914.7,
      "biggestCm": 2940.3
    },
    {
      "id": 2,
      "name": "Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "The Legend of Schrade",
      "biggestPct": 105,
      "biggestQuest": "The Legend of Schrade",
      "questCount": 2
    },
    {
      "id": 28,
      "name": "Gendrome",
      "baseCm": 732.1,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 89,
      "smallestQuest": "Pursuit of the Sand Wyvern",
      "biggestPct": 131,
      "biggestQuest": "Pursuit of the Sand Wyvern",
      "questCount": 13,
      "minCrownCm": 658.9,
      "kingCrownCm": 900.5,
      "smallestCm": 653.4,
      "biggestCm": 960.9
    },
    {
      "id": 77,
      "name": "Giadrome",
      "baseCm": 738.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 88,
      "smallestQuest": "A True Foe - The Giadrome!",
      "biggestPct": 130,
      "biggestQuest": "A True Foe - The Giadrome!",
      "questCount": 12,
      "minCrownCm": 664.6,
      "kingCrownCm": 908.2,
      "smallestCm": 652.7,
      "biggestCm": 959.9
    },
    {
      "id": 42,
      "name": "Gold Rathian",
      "baseCm": 1645.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 94,
      "smallestQuest": "Anger of Heaven and Earth",
      "biggestPct": 140,
      "biggestQuest": "Find the Golden Phantom",
      "questCount": 2,
      "minCrownCm": 1530.4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1538.6,
      "biggestCm": 2303.8
    },
    {
      "id": 17,
      "name": "Gravios",
      "baseCm": 2099.9,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.35,
      "smallestPct": 95,
      "smallestQuest": "Terror of the Gravios",
      "biggestPct": 140,
      "biggestQuest": "Terror of the Gravios",
      "questCount": 5,
      "minCrownCm": 2036.9,
      "kingCrownCm": 2834.9,
      "smallestCm": 1999.1,
      "biggestCm": 2939.9
    },
    {
      "id": 46,
      "name": "Green Plesioth",
      "baseCm": 2315.2,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.34,
      "smallestPct": 94,
      "smallestQuest": "Dual Plesioth",
      "biggestPct": 140,
      "biggestQuest": "Dual Plesioth",
      "questCount": 5,
      "minCrownCm": 2245.7,
      "kingCrownCm": 3102.4,
      "smallestCm": 2164.7,
      "biggestCm": 3241.3
    },
    {
      "id": 20,
      "name": "Gypceros",
      "baseCm": 1013.7,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.25,
      "smallestPct": 91,
      "smallestQuest": "Concerto of Light & Poison",
      "biggestPct": 134,
      "biggestQuest": "Concerto of Light & Poison",
      "questCount": 9,
      "minCrownCm": 942.7,
      "kingCrownCm": 1267.1,
      "smallestCm": 922,
      "biggestCm": 1355.8
    },
    {
      "id": 31,
      "name": "Iodrome",
      "baseCm": 774.6,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.36,
      "smallestPct": 89,
      "smallestQuest": "Basarios: Unseen Peril",
      "biggestPct": 145,
      "biggestQuest": "The Remobra Den",
      "questCount": 10,
      "minCrownCm": 697.1,
      "kingCrownCm": 1053.5,
      "smallestCm": 691.3,
      "biggestCm": 1123.2
    },
    {
      "id": 15,
      "name": "Khezu",
      "baseCm": 873.2,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.35,
      "smallestPct": 50,
      "smallestQuest": "電撃祭　２ｎｄ！",
      "biggestPct": 136,
      "biggestQuest": "The Electrified Wyvern",
      "questCount": 7,
      "minCrownCm": 812.1,
      "kingCrownCm": 1178.8,
      "smallestCm": 436.6,
      "biggestCm": 1189.7
    },
    {
      "id": 33,
      "name": "Kirin",
      "baseCm": 464.3,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.77,
      "smallestPct": 96,
      "smallestQuest": "The Legendary Kirin",
      "biggestPct": 188,
      "biggestQuest": "The White Brute",
      "questCount": 7,
      "minCrownCm": 450.4,
      "kingCrownCm": 821.8,
      "smallestCm": 445.5,
      "biggestCm": 870.6
    },
    {
      "id": 54,
      "name": "Kushala Daora",
      "baseCm": 1577,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.2,
      "smallestPct": 90,
      "smallestQuest": "The Frozen Dictator",
      "biggestPct": 133,
      "biggestQuest": "The Frozen Dictator",
      "questCount": 5,
      "minCrownCm": 1435.1,
      "kingCrownCm": 1892.4,
      "smallestCm": 1419.3,
      "biggestCm": 2097.4
    },
    {
      "id": 7,
      "name": "Lao-Shan Lung",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "A Giant Dragon Invades!",
      "biggestPct": 100,
      "biggestQuest": "A Giant Dragon Invades!",
      "questCount": 1
    },
    {
      "id": 64,
      "name": "Lunastra",
      "baseCm": 1740,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.21,
      "smallestPct": 87,
      "smallestQuest": "The Empress' Blazing Throne",
      "biggestPct": 128,
      "biggestQuest": "The Empress' Blazing Throne",
      "questCount": 2,
      "minCrownCm": 1583.4,
      "kingCrownCm": 2105.4,
      "smallestCm": 1508.6,
      "biggestCm": 2218.5
    },
    {
      "id": 26,
      "name": "Monoblos",
      "baseCm": 2004.2,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.27,
      "smallestPct": 95,
      "smallestQuest": "Battle of the Blos",
      "biggestPct": 114,
      "biggestQuest": "Battle of the Blos",
      "questCount": 1,
      "minCrownCm": 1883.9,
      "kingCrownCm": 2545.3,
      "smallestCm": 1904,
      "biggestCm": 2284.8
    },
    {
      "id": 60,
      "name": "Rusted Kushala Daora",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 89,
      "smallestQuest": "Attack of the Wind Dragon",
      "biggestPct": 134,
      "biggestQuest": "The Visitor of Steel",
      "questCount": 2
    },
    {
      "id": 40,
      "name": "Yian Garuga",
      "baseCm": 1031.7,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.21,
      "smallestPct": 87,
      "smallestQuest": "Scarface",
      "biggestPct": 128,
      "biggestQuest": "Scarface",
      "questCount": 4,
      "minCrownCm": 938.8,
      "kingCrownCm": 1248.4,
      "smallestCm": 894.5,
      "biggestCm": 1315.4
    },
    {
      "id": 37,
      "name": "Pink Rathian",
      "baseCm": 1645.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 89,
      "smallestQuest": "Pink Dance in the Jungle",
      "biggestPct": 140,
      "biggestQuest": "Blue Sky, Pink Earth",
      "questCount": 5,
      "minCrownCm": 1530.4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1468.7,
      "biggestCm": 2303.8
    },
    {
      "id": 21,
      "name": "Plesioth",
      "baseCm": 2315.2,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.34,
      "smallestPct": 94,
      "smallestQuest": "Dual Plesioth",
      "biggestPct": 140,
      "biggestQuest": "Dual Plesioth",
      "questCount": 9,
      "minCrownCm": 2245.7,
      "kingCrownCm": 3102.4,
      "smallestCm": 2164.7,
      "biggestCm": 3241.3
    },
    {
      "id": 39,
      "name": "Purple Gypceros",
      "baseCm": 1013.7,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.25,
      "smallestPct": 91,
      "smallestQuest": "The Poison Gas",
      "biggestPct": 134,
      "biggestQuest": "The Poison Gas",
      "questCount": 6,
      "minCrownCm": 942.7,
      "kingCrownCm": 1267.1,
      "smallestCm": 922,
      "biggestCm": 1355.8
    },
    {
      "id": 53,
      "name": "Rajang",
      "baseCm": 960,
      "minCrownPct": 1.05,
      "kingCrownPct": 1.4,
      "smallestPct": 100,
      "smallestQuest": "The Final Invitation",
      "biggestPct": 163,
      "biggestQuest": "Rajang of Mountain Flames",
      "questCount": 6,
      "minCrownCm": 1008,
      "kingCrownCm": 1344,
      "smallestCm": 960,
      "biggestCm": 1564.8
    },
    {
      "id": 11,
      "name": "Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.27,
      "smallestPct": 88,
      "smallestQuest": "A Troublesome Pair",
      "biggestPct": 130,
      "biggestQuest": "A Troublesome Pair",
      "questCount": 9,
      "minCrownCm": 1466.5,
      "kingCrownCm": 2069.3,
      "smallestCm": 1440.4,
      "biggestCm": 2118.2
    },
    {
      "id": 1,
      "name": "Rathian",
      "baseCm": 1645.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 88,
      "smallestQuest": "A Troublesome Pair",
      "biggestPct": 138,
      "biggestQuest": "ファミ通　２頭の女王",
      "questCount": 14,
      "minCrownCm": 1530.4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1454.7,
      "biggestCm": 2262.7
    },
    {
      "id": 45,
      "name": "Red Khezu",
      "baseCm": 873.2,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.35,
      "smallestPct": 93,
      "smallestQuest": "Red Shadow on the Swamp",
      "biggestPct": 136,
      "biggestQuest": "Red Shadow on the Swamp",
      "questCount": 3,
      "minCrownCm": 812.1,
      "kingCrownCm": 1178.8,
      "smallestCm": 809,
      "biggestCm": 1189.7
    },
    {
      "id": 55,
      "name": "Shen Gaoren",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "The Approaching Gaoren",
      "biggestPct": 100,
      "biggestQuest": "The Approaching Gaoren",
      "questCount": 3
    },
    {
      "id": 67,
      "name": "Shogun Ceanataur",
      "baseCm": 863,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.2,
      "smallestPct": 87,
      "smallestQuest": "The Shogun's Encampment",
      "biggestPct": 150,
      "biggestQuest": "The Shogun's Encampment",
      "questCount": 16,
      "minCrownCm": 811.2,
      "kingCrownCm": 1035.6,
      "smallestCm": 748.2,
      "biggestCm": 1294.5
    },
    {
      "id": 41,
      "name": "Silver Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.27,
      "smallestPct": 94,
      "smallestQuest": "Anger of Heaven and Earth",
      "biggestPct": 138,
      "biggestQuest": "Anger of Heaven and Earth",
      "questCount": 2,
      "minCrownCm": 1466.5,
      "kingCrownCm": 2069.3,
      "smallestCm": 1523.5,
      "biggestCm": 2240.4
    },
    {
      "id": 65,
      "name": "Teostra",
      "baseCm": 1740,
      "minCrownPct": 0.88,
      "kingCrownPct": 1.25,
      "smallestPct": 87,
      "smallestQuest": "A Sun with Fangs",
      "biggestPct": 134,
      "biggestQuest": "ＪＵＭＰ　炎帝の凱旋",
      "questCount": 12,
      "minCrownCm": 1531.2,
      "kingCrownCm": 2175,
      "smallestCm": 1508.6,
      "biggestCm": 2327.2
    },
    {
      "id": 75,
      "name": "Tigrex",
      "baseCm": 1735.3,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 88,
      "smallestQuest": "The Tigrex's Roar",
      "biggestPct": 130,
      "biggestQuest": "The Tigrex's Roar",
      "questCount": 13,
      "minCrownCm": 1561.8,
      "kingCrownCm": 2134.4,
      "smallestCm": 1534,
      "biggestCm": 2255.9
    },
    {
      "id": 27,
      "name": "Velocidrome",
      "baseCm": 738.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 88,
      "smallestQuest": "Flanked by Velocidrome",
      "biggestPct": 130,
      "biggestQuest": "Flanked by Velocidrome",
      "questCount": 15,
      "minCrownCm": 664.6,
      "kingCrownCm": 908.2,
      "smallestCm": 652.7,
      "biggestCm": 959.9
    },
    {
      "id": 71,
      "name": "White Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Ancestral Dragon",
      "biggestPct": 105,
      "biggestQuest": "Ancestral Dragon",
      "questCount": 2
    },
    {
      "id": 44,
      "name": "White Monoblos",
      "baseCm": 2004.2,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.27,
      "smallestPct": 94,
      "smallestQuest": "The Silver Horn",
      "biggestPct": 138,
      "biggestQuest": "The Silver Horn",
      "questCount": 1,
      "minCrownCm": 1883.9,
      "kingCrownCm": 2545.3,
      "smallestCm": 1873.9,
      "biggestCm": 2755.8
    },
    {
      "id": 6,
      "name": "Yian Kut-Ku",
      "baseCm": 919.8,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.22,
      "smallestPct": 50,
      "smallestQuest": "The Mysterious Kut-Ku",
      "biggestPct": 128,
      "biggestQuest": "Trapped by Yian Kut-Ku ",
      "questCount": 14,
      "minCrownCm": 827.8,
      "kingCrownCm": 1122.2,
      "smallestCm": 459.9,
      "biggestCm": 1172.7
    }
  ],
  "mhfu": [
    {
      "id": 76,
      "name": "Akantor",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "High Altitude King",
      "biggestPct": 100,
      "biggestQuest": "High Altitude King",
      "questCount": 3
    },
    {
      "id": 50,
      "name": "Ashen Lao-Shan Lung",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Lao-Shan Lung Draws Near!",
      "biggestPct": 100,
      "biggestQuest": "Lao-Shan Lung Draws Near!",
      "questCount": 3
    },
    {
      "id": 49,
      "name": "Azure Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.27,
      "smallestPct": 88,
      "smallestQuest": "Attack of the Rathalos",
      "biggestPct": 140,
      "biggestQuest": "Blue Sky, Pink Earth",
      "questCount": 7,
      "minCrownCm": 1466.5,
      "kingCrownCm": 2069.3,
      "smallestCm": 1440.4,
      "biggestCm": 2281.2
    },
    {
      "id": 22,
      "name": "Basarios",
      "baseCm": 1297.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 89,
      "smallestQuest": "Basarios: Unseen Peril",
      "biggestPct": 134,
      "biggestQuest": "G-Lvl Gathering - OldVolcano",
      "questCount": 12,
      "minCrownCm": 1206.8,
      "kingCrownCm": 1673.9,
      "smallestCm": 1158.1,
      "biggestCm": 1735.5
    },
    {
      "id": 43,
      "name": "Black Diablos",
      "baseCm": 1993.4,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.39,
      "smallestPct": 95,
      "smallestQuest": "The Four Spires",
      "biggestPct": 150,
      "biggestQuest": "Dual Twin Horns - Arena",
      "questCount": 12,
      "minCrownCm": 1933.6,
      "kingCrownCm": 2770.8,
      "smallestCm": 1897.7,
      "biggestCm": 2990.1
    },
    {
      "id": 47,
      "name": "Black Gravios",
      "baseCm": 2099.9,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.35,
      "smallestPct": 94,
      "smallestQuest": "Black Rock in the Swamp",
      "biggestPct": 144,
      "biggestQuest": "Two Cliffs! Dark Hot Winds",
      "questCount": 9,
      "minCrownCm": 2036.9,
      "kingCrownCm": 2834.9,
      "smallestCm": 1963.4,
      "biggestCm": 3018.6
    },
    {
      "id": 51,
      "name": "Blangonga",
      "baseCm": 860,
      "minCrownPct": 0.99,
      "kingCrownPct": 1.38,
      "smallestPct": 97,
      "smallestQuest": "The King of the Mountains",
      "biggestPct": 144,
      "biggestQuest": "The King of the Mountains",
      "questCount": 14,
      "minCrownCm": 851.4,
      "kingCrownCm": 1186.8,
      "smallestCm": 833.3,
      "biggestCm": 1236.2
    },
    {
      "id": 38,
      "name": "Blue Yian Kut-Ku",
      "baseCm": 919.8,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.22,
      "smallestPct": 87,
      "smallestQuest": "Trapped by Yian Kut-Ku ",
      "biggestPct": 131,
      "biggestQuest": "G-Lvl Gathering - Frst&Hills",
      "questCount": 14,
      "minCrownCm": 827.8,
      "kingCrownCm": 1122.2,
      "smallestCm": 797.5,
      "biggestCm": 1207.2
    },
    {
      "id": 68,
      "name": "Bulldrome",
      "baseCm": 566,
      "minCrownPct": 0.98,
      "kingCrownPct": 1.3,
      "smallestPct": 89,
      "smallestQuest": "The Purple Poison Menace",
      "biggestPct": 210,
      "biggestQuest": "Challenge Quest 5",
      "questCount": 19,
      "minCrownCm": 554.7,
      "kingCrownCm": 735.8,
      "smallestCm": 505.2,
      "biggestCm": 1188.6
    },
    {
      "id": 8,
      "name": "Cephadrome",
      "baseCm": 1538.3,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.22,
      "smallestPct": 89,
      "smallestQuest": "Pursuit of the Sand Wyvern",
      "biggestPct": 131,
      "biggestQuest": "Pursuit of the Sand Wyvern",
      "questCount": 9,
      "minCrownCm": 1430.6,
      "kingCrownCm": 1876.7,
      "smallestCm": 1372.9,
      "biggestCm": 2019
    },
    {
      "id": 59,
      "name": "Chameleos",
      "baseCm": 1744,
      "minCrownPct": 0.96,
      "kingCrownPct": 1.41,
      "smallestPct": 95,
      "smallestQuest": "The Elder Dragon of Mist",
      "biggestPct": 152,
      "biggestQuest": "Evaporate into the Night",
      "questCount": 9,
      "minCrownCm": 1674.2,
      "kingCrownCm": 2459,
      "smallestCm": 1656.8,
      "biggestCm": 2644.3
    },
    {
      "id": 52,
      "name": "Congalala",
      "baseCm": 984,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.25,
      "smallestPct": 94,
      "smallestQuest": "Conga Counterattack!",
      "biggestPct": 140,
      "biggestQuest": "Expunge the Funk!",
      "questCount": 22,
      "minCrownCm": 954.5,
      "kingCrownCm": 1230,
      "smallestCm": 920,
      "biggestCm": 1377.6
    },
    {
      "id": 84,
      "name": "Copper Blangonga",
      "baseCm": 860,
      "minCrownPct": 0.99,
      "kingCrownPct": 1.38,
      "smallestPct": 94,
      "smallestQuest": "Copper Sands",
      "biggestPct": 145,
      "biggestQuest": "Wild Monk of the Dunes",
      "questCount": 5,
      "minCrownCm": 851.4,
      "kingCrownCm": 1186.8,
      "smallestCm": 804.1,
      "biggestCm": 1247
    },
    {
      "id": 36,
      "name": "Crimson Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Scarlet Skies",
      "biggestPct": 100,
      "biggestQuest": "Scarlet Skies",
      "questCount": 3
    },
    {
      "id": 48,
      "name": "Daimyo Hermitaur",
      "baseCm": 1044,
      "minCrownPct": 0.88,
      "kingCrownPct": 1.23,
      "smallestPct": 85,
      "smallestQuest": "Ultimate Crab Dinner",
      "biggestPct": 128,
      "biggestQuest": "Wag the Dog!",
      "questCount": 25,
      "minCrownCm": 918.7,
      "kingCrownCm": 1284.1,
      "smallestCm": 887.4,
      "biggestCm": 1331.1
    },
    {
      "id": 14,
      "name": "Diablos",
      "baseCm": 1993.4,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.39,
      "smallestPct": 96,
      "smallestQuest": "Four Horns",
      "biggestPct": 154,
      "biggestQuest": "Demon King Returns!",
      "questCount": 15,
      "minCrownCm": 1933.6,
      "kingCrownCm": 2770.8,
      "smallestCm": 1914.7,
      "biggestCm": 3071.8
    },
    {
      "id": 85,
      "name": "Emerald Congalala",
      "baseCm": 984,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.25,
      "smallestPct": 95,
      "smallestQuest": "Expunge the Funk!",
      "biggestPct": 140,
      "biggestQuest": "Expunge the Funk!",
      "questCount": 9,
      "minCrownCm": 954.5,
      "kingCrownCm": 1230,
      "smallestCm": 936.8,
      "biggestCm": 1377.6
    },
    {
      "id": 2,
      "name": "Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Black Wings of Fate",
      "biggestPct": 100,
      "biggestQuest": "Black Wings of Fate",
      "questCount": 3
    },
    {
      "id": 89,
      "name": "Furious Rajang",
      "baseCm": 960,
      "minCrownPct": 1.05,
      "kingCrownPct": 1.4,
      "smallestPct": 100,
      "smallestQuest": "Challenge Quest 10",
      "biggestPct": 150,
      "biggestQuest": "Child of Destruction",
      "questCount": 6,
      "minCrownCm": 1008,
      "kingCrownCm": 1344,
      "smallestCm": 960,
      "biggestCm": 1440
    },
    {
      "id": 28,
      "name": "Gendrome",
      "baseCm": 732.1,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 89,
      "smallestQuest": "Pursuit of the Sand Wyvern",
      "biggestPct": 131,
      "biggestQuest": "Pursuit of the Sand Wyvern",
      "questCount": 13,
      "minCrownCm": 658.9,
      "kingCrownCm": 900.5,
      "smallestCm": 653.4,
      "biggestCm": 960.9
    },
    {
      "id": 77,
      "name": "Giadrome",
      "baseCm": 738.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 88,
      "smallestQuest": "A True Foe - The Giadrome!",
      "biggestPct": 135,
      "biggestQuest": "Red Shadow in the Snow",
      "questCount": 14,
      "minCrownCm": 664.6,
      "kingCrownCm": 908.2,
      "smallestCm": 652.7,
      "biggestCm": 996.8
    },
    {
      "id": 42,
      "name": "Gold Rathian",
      "baseCm": 1645.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 92,
      "smallestQuest": "Fire Ring, Lunar Ring",
      "biggestPct": 140,
      "biggestQuest": "A Single Beam of Moonlight",
      "questCount": 5,
      "minCrownCm": 1530.4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1510.7,
      "biggestCm": 2303.8
    },
    {
      "id": 17,
      "name": "Gravios",
      "baseCm": 2099.9,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.35,
      "smallestPct": 94,
      "smallestQuest": "Armored Supremacy",
      "biggestPct": 141,
      "biggestQuest": "Armored Supremacy",
      "questCount": 12,
      "minCrownCm": 2036.9,
      "kingCrownCm": 2834.9,
      "smallestCm": 1981.3,
      "biggestCm": 2966.1
    },
    {
      "id": 46,
      "name": "Green Plesioth",
      "baseCm": 2315.2,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.34,
      "smallestPct": 94,
      "smallestQuest": "Dual Plesioth",
      "biggestPct": 140,
      "biggestQuest": "Giant Green Waves of Verdure",
      "questCount": 12,
      "minCrownCm": 2245.7,
      "kingCrownCm": 3102.4,
      "smallestCm": 2164.7,
      "biggestCm": 3248.2
    },
    {
      "id": 20,
      "name": "Gypceros",
      "baseCm": 1013.7,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.25,
      "smallestPct": 88,
      "smallestQuest": "Stealing in the Old Swamp!",
      "biggestPct": 134,
      "biggestQuest": "Stealing in the Jungle!",
      "questCount": 11,
      "minCrownCm": 942.7,
      "kingCrownCm": 1267.1,
      "smallestCm": 896.1,
      "biggestCm": 1355.8
    },
    {
      "id": 82,
      "name": "Hypnocatrice",
      "baseCm": 834.9,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.21,
      "smallestPct": 88,
      "smallestQuest": "The Big Dirt Nap",
      "biggestPct": 141,
      "biggestQuest": "Hypno, Hypno!",
      "questCount": 13,
      "minCrownCm": 759.8,
      "kingCrownCm": 1010.2,
      "smallestCm": 738.1,
      "biggestCm": 1179.3
    },
    {
      "id": 31,
      "name": "Iodrome",
      "baseCm": 774.6,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.36,
      "smallestPct": 89,
      "smallestQuest": "Basarios: Unseen Peril",
      "biggestPct": 145,
      "biggestQuest": "An Evening Soaked in Poison",
      "questCount": 12,
      "minCrownCm": 697.1,
      "kingCrownCm": 1053.5,
      "smallestCm": 691.3,
      "biggestCm": 1123.2
    },
    {
      "id": 15,
      "name": "Khezu",
      "baseCm": 873.2,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.35,
      "smallestPct": 50,
      "smallestQuest": "Small Shadow over the Swamp",
      "biggestPct": 139,
      "biggestQuest": "Old Jungle Lightning",
      "questCount": 15,
      "minCrownCm": 812.1,
      "kingCrownCm": 1178.8,
      "smallestCm": 436.6,
      "biggestCm": 1211.6
    },
    {
      "id": 33,
      "name": "Kirin",
      "baseCm": 464.3,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.77,
      "smallestPct": 96,
      "smallestQuest": "The Legendary Kirin",
      "biggestPct": 200,
      "biggestQuest": "A Scenic Locale",
      "questCount": 10,
      "minCrownCm": 450.4,
      "kingCrownCm": 821.8,
      "smallestCm": 445.5,
      "biggestCm": 929.1
    },
    {
      "id": 54,
      "name": "Kushala Daora",
      "baseCm": 1577,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.2,
      "smallestPct": 90,
      "smallestQuest": "The Elder Dragon of Wind",
      "biggestPct": 138,
      "biggestQuest": "Famitsu: Snowstorm Raider",
      "questCount": 7,
      "minCrownCm": 1435.1,
      "kingCrownCm": 1892.4,
      "smallestCm": 1420.9,
      "biggestCm": 2176.3
    },
    {
      "id": 7,
      "name": "Lao-Shan Lung",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "A Giant Dragon Invades!",
      "biggestPct": 100,
      "biggestQuest": "A Giant Dragon Invades!",
      "questCount": 2
    },
    {
      "id": 83,
      "name": "Lavasioth",
      "baseCm": 2223.2,
      "minCrownPct": 0.85,
      "kingCrownPct": 1.16,
      "smallestPct": 82,
      "smallestQuest": "River of Fire",
      "biggestPct": 128,
      "biggestQuest": "Surrounded in a Sea of Magma",
      "questCount": 6,
      "minCrownCm": 1889.7,
      "kingCrownCm": 2578.9,
      "smallestCm": 1814.1,
      "biggestCm": 2847.9
    },
    {
      "id": 64,
      "name": "Lunastra",
      "baseCm": 1740,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.21,
      "smallestPct": 87,
      "smallestQuest": "Overseer of the Ancients",
      "biggestPct": 130,
      "biggestQuest": "Indigo Meteor",
      "questCount": 4,
      "minCrownCm": 1583.4,
      "kingCrownCm": 2105.4,
      "smallestCm": 1508.6,
      "biggestCm": 2262
    },
    {
      "id": 26,
      "name": "Monoblos",
      "baseCm": 2004.2,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.27,
      "smallestPct": 94,
      "smallestQuest": "Battle with the Monoblos",
      "biggestPct": 140,
      "biggestQuest": "Secret Request: 2 Monoblos!",
      "questCount": 4,
      "minCrownCm": 1883.9,
      "kingCrownCm": 2545.3,
      "smallestCm": 1873.9,
      "biggestCm": 2805.9
    },
    {
      "id": 58,
      "name": "Yama Tsukami",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Mountain in the Sky",
      "biggestPct": 100,
      "biggestQuest": "Mountain in the Sky",
      "questCount": 2
    },
    {
      "id": 60,
      "name": "Rusted Kushala Daora",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 88,
      "smallestQuest": "Attack of the Wind Dragon",
      "biggestPct": 131,
      "biggestQuest": "Attack of the Wind Dragon",
      "questCount": 2
    },
    {
      "id": 79,
      "name": "King Shakalaka",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 87,
      "smallestQuest": "Ever-Present Shadow",
      "biggestPct": 140,
      "biggestQuest": "The King's Domain",
      "questCount": 8
    },
    {
      "id": 80,
      "name": "Queen Vespoid",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 87,
      "smallestQuest": "G-Lvl Gathering - Old Jungle",
      "biggestPct": 128,
      "biggestQuest": "G-Lvl Gathering - Old Jungle",
      "questCount": 5
    },
    {
      "id": 81,
      "name": "Nargacuga",
      "baseCm": 1602.2,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 87,
      "smallestQuest": "Assassin of the Swamp",
      "biggestPct": 131,
      "biggestQuest": "Ancient Beauty, Black Beast",
      "questCount": 17,
      "minCrownCm": 1442,
      "kingCrownCm": 1970.7,
      "smallestCm": 1389.1,
      "biggestCm": 2102.9
    },
    {
      "id": 40,
      "name": "Yian Garuga",
      "baseCm": 1031.7,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.21,
      "smallestPct": 88,
      "smallestQuest": "Elegy for a Lone Wolf",
      "biggestPct": 130,
      "biggestQuest": "Howling at the Moon",
      "questCount": 3,
      "minCrownCm": 938.8,
      "kingCrownCm": 1248.4,
      "smallestCm": 903.3,
      "biggestCm": 1341.2
    },
    {
      "id": 37,
      "name": "Pink Rathian",
      "baseCm": 1645.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 89,
      "smallestQuest": "Pink Dance in the Jungle",
      "biggestPct": 140,
      "biggestQuest": "Blue Sky, Pink Earth",
      "questCount": 10,
      "minCrownCm": 1530.4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1468.7,
      "biggestCm": 2303.8
    },
    {
      "id": 21,
      "name": "Plesioth",
      "baseCm": 2315.2,
      "minCrownPct": 0.97,
      "kingCrownPct": 1.34,
      "smallestPct": 94,
      "smallestQuest": "Dual Plesioth",
      "biggestPct": 140,
      "biggestQuest": "Dual Plesioth",
      "questCount": 15,
      "minCrownCm": 2245.7,
      "kingCrownCm": 3102.4,
      "smallestCm": 2164.7,
      "biggestCm": 3241.3
    },
    {
      "id": 86,
      "name": "Plum Daimyo Hermitaur",
      "baseCm": 1044,
      "minCrownPct": 0.88,
      "kingCrownPct": 1.23,
      "smallestPct": 86,
      "smallestQuest": "Daimyo of Sengoku Fame",
      "biggestPct": 128,
      "biggestQuest": "Amezari Carnival!",
      "questCount": 6,
      "minCrownCm": 918.7,
      "kingCrownCm": 1284.1,
      "smallestCm": 896.3,
      "biggestCm": 1331.1
    },
    {
      "id": 39,
      "name": "Purple Gypceros",
      "baseCm": 1013.7,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.25,
      "smallestPct": 89,
      "smallestQuest": "The Purple Poison Menace",
      "biggestPct": 135,
      "biggestQuest": "Old Swamp, Shrouded in Mist",
      "questCount": 9,
      "minCrownCm": 942.7,
      "kingCrownCm": 1267.1,
      "smallestCm": 904.7,
      "biggestCm": 1368.5
    },
    {
      "id": 53,
      "name": "Rajang",
      "baseCm": 960,
      "minCrownPct": 1.05,
      "kingCrownPct": 1.4,
      "smallestPct": 95,
      "smallestQuest": "Demon's Teardrop Mountain",
      "biggestPct": 162,
      "biggestQuest": "Rajang of Mountain Flames",
      "questCount": 9,
      "minCrownCm": 1008,
      "kingCrownCm": 1344,
      "smallestCm": 913.9,
      "biggestCm": 1560
    },
    {
      "id": 11,
      "name": "Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.27,
      "smallestPct": 88,
      "smallestQuest": "A Troublesome Pair",
      "biggestPct": 135,
      "biggestQuest": "A King, Robed in Smoke",
      "questCount": 14,
      "minCrownCm": 1466.5,
      "kingCrownCm": 2069.3,
      "smallestCm": 1440.4,
      "biggestCm": 2199.7
    },
    {
      "id": 1,
      "name": "Rathian",
      "baseCm": 1645.6,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.29,
      "smallestPct": 88,
      "smallestQuest": "A Troublesome Pair",
      "biggestPct": 131,
      "biggestQuest": "Her Eternal Majesty",
      "questCount": 16,
      "minCrownCm": 1530.4,
      "kingCrownCm": 2122.8,
      "smallestCm": 1454.7,
      "biggestCm": 2159.8
    },
    {
      "id": 45,
      "name": "Red Khezu",
      "baseCm": 873.2,
      "minCrownPct": 0.93,
      "kingCrownPct": 1.35,
      "smallestPct": 92,
      "smallestQuest": "Red Shadow in the Snow",
      "biggestPct": 139,
      "biggestQuest": "Tales from the Old Swamp",
      "questCount": 11,
      "minCrownCm": 812.1,
      "kingCrownCm": 1178.8,
      "smallestCm": 801.6,
      "biggestCm": 1211.6
    },
    {
      "id": 55,
      "name": "Shen Gaoren",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "The Approaching Gaoren",
      "biggestPct": 100,
      "biggestQuest": "The Approaching Gaoren",
      "questCount": 4
    },
    {
      "id": 67,
      "name": "Shogun Ceanataur",
      "baseCm": 863,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.2,
      "smallestPct": 87,
      "smallestQuest": "Commander in the Flames",
      "biggestPct": 150,
      "biggestQuest": "The Shogun's Encampment",
      "questCount": 23,
      "minCrownCm": 811.2,
      "kingCrownCm": 1035.6,
      "smallestCm": 748.2,
      "biggestCm": 1294.5
    },
    {
      "id": 41,
      "name": "Silver Rathalos",
      "baseCm": 1629.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.27,
      "smallestPct": 92,
      "smallestQuest": "Explore the Unexplored",
      "biggestPct": 140,
      "biggestQuest": "Explore the Unexplored",
      "questCount": 5,
      "minCrownCm": 1466.5,
      "kingCrownCm": 2069.3,
      "smallestCm": 1495.8,
      "biggestCm": 2281.2
    },
    {
      "id": 65,
      "name": "Teostra",
      "baseCm": 1740,
      "minCrownPct": 0.88,
      "kingCrownPct": 1.25,
      "smallestPct": 87,
      "smallestQuest": "A Sun with Fangs",
      "biggestPct": 140,
      "biggestQuest": "JUMP: Emperor of Explosions",
      "questCount": 11,
      "minCrownCm": 1531.2,
      "kingCrownCm": 2175,
      "smallestCm": 1508.6,
      "biggestCm": 2441.2
    },
    {
      "id": 87,
      "name": "Terra Shogun Ceanataur",
      "baseCm": 863,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.2,
      "smallestPct": 87,
      "smallestQuest": "Amezari Carnival!",
      "biggestPct": 130,
      "biggestQuest": "Dark-Shelled Ceanataur",
      "questCount": 9,
      "minCrownCm": 811.2,
      "kingCrownCm": 1035.6,
      "smallestCm": 748.2,
      "biggestCm": 1121.9
    },
    {
      "id": 75,
      "name": "Tigrex",
      "baseCm": 1735.3,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 88,
      "smallestQuest": "The Tigrex's Roar",
      "biggestPct": 138,
      "biggestQuest": "Magazine: Tyranny of Tigrex",
      "questCount": 24,
      "minCrownCm": 1561.8,
      "kingCrownCm": 2134.4,
      "smallestCm": 1534,
      "biggestCm": 2394.7
    },
    {
      "id": 88,
      "name": "Ukanlos",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "Absolute Zero",
      "biggestPct": 100,
      "biggestQuest": "Absolute Zero",
      "questCount": 1
    },
    {
      "id": 27,
      "name": "Velocidrome",
      "baseCm": 738.4,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.23,
      "smallestPct": 88,
      "smallestQuest": "Flanked by Velocidrome",
      "biggestPct": 130,
      "biggestQuest": "Flanked by Velocidrome",
      "questCount": 13,
      "minCrownCm": 664.6,
      "kingCrownCm": 908.2,
      "smallestCm": 652.7,
      "biggestCm": 959.9
    },
    {
      "id": 71,
      "name": "White Fatalis",
      "baseCm": null,
      "minCrownPct": null,
      "kingCrownPct": null,
      "smallestPct": 100,
      "smallestQuest": "The Big Daddy",
      "biggestPct": 100,
      "biggestQuest": "The Big Daddy",
      "questCount": 4
    },
    {
      "id": 44,
      "name": "White Monoblos",
      "baseCm": 2004.2,
      "minCrownPct": 0.94,
      "kingCrownPct": 1.27,
      "smallestPct": 94,
      "smallestQuest": "The Silver Horn",
      "biggestPct": 140,
      "biggestQuest": "Secret Request: 2 Monoblos!",
      "questCount": 3,
      "minCrownCm": 1883.9,
      "kingCrownCm": 2545.3,
      "smallestCm": 1873.9,
      "biggestCm": 2805.9
    },
    {
      "id": 78,
      "name": "Yian Garuga",
      "baseCm": 1031.7,
      "minCrownPct": 0.91,
      "kingCrownPct": 1.21,
      "smallestPct": 87,
      "smallestQuest": "The Lone Black Garuga",
      "biggestPct": 130,
      "biggestQuest": "The Yian Garuga Twins",
      "questCount": 8,
      "minCrownCm": 938.8,
      "kingCrownCm": 1248.4,
      "smallestCm": 894.5,
      "biggestCm": 1341.2
    },
    {
      "id": 6,
      "name": "Yian Kut-Ku",
      "baseCm": 919.8,
      "minCrownPct": 0.9,
      "kingCrownPct": 1.22,
      "smallestPct": 50,
      "smallestQuest": "Its name is \"Mega Kut-Ku\"!?",
      "biggestPct": 130,
      "biggestQuest": "Trapped by Yian Kut-Ku ",
      "questCount": 21,
      "minCrownCm": 827.8,
      "kingCrownCm": 1122.2,
      "smallestCm": 459.9,
      "biggestCm": 1195.7
    }
  ]
};
